apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-processor-11885
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/gateway-processor-11885
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
